language: node_js
node_js:
  - '10'
  - '9'
  - '8'

services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
script: "npm run lint && npm run coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
