language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=travis
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
script: "npm run coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
