version: '2'

services:
  app:
    build:
      context: docker/node
    environment:
      - CONFIG_WEB_USERNAME=u
      - CONFIG_WEB_PASSWORD=p
      - DEBUG=pushserver:*
      - MONGO_URI=mongodb://mongo/pushserver
      - REDIS_URL=http://redis:6379
    links:
      - mongo
      - redis
    ports:
      - "18080:18080"
    volumes:
      - .:/app

  mongo:
    image: mongo:3.6.5
    volumes:
      - .:/app:ro
      - ./docker/data/mongo:/data/db

  redis:
    image: redis:4.0.9-alpine
    command: redis-server --appendonly yes
    volumes:
      - .:/app:ro
      - ./docker/data/redis:/data
